### ISSUE TITLE
Use EVA to generate the relevant obs space plot for 1 DA cycle

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#316]
## Descriptiuon
Use the existing python tool in the GDASApp [gen_eva_obs_yaml.py](https://github.com/NOAA-EMC/GDASApp/blob/develop/ush/eva/gen_eva_obs_yaml.py) to generate marine DA EVA yaml files ...

- [x] get a valid `var.yaml` file from an existing experiments (this is the input to the script above)
- [x] create eva templates for the marine obs 
- [x] test the generated yaml with eva

## Notes
You can find a low-res experiments on `Hera` here:
```console
/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/runs/test4jakir/
```
The  `var.yaml` (as I understand, the input to `gen_eva_obs_yaml.py`) is here:
```console
/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/runs/test4jakir/analysis/var.yaml
```
and the ioda output files are here:
```console
/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/runs/test4jakir/analysis/diags
```

**Comment by mjhossen** [comment]
Thanks @guillaumevernieres

**Comment by mjhossen** [comment]
@guillaumevernieres I am wondering how var.yaml is generated. Is it generated by the system automatically and put in the analysis folder?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres I am wondering how var.yaml is generated. Is it generated by the system automatically and put in the analysis folder?

Exactly @mjhossen

**Comment by mjhossen** [comment]
@guillaumevernieres The python tool [gen_eva_obs_yaml.py](https://github.com/NOAA-EMC/GDASApp/blob/develop/ush/eva/gen_eva_obs_yaml.py) provides an error message. It seems it does not like var.yaml file. Either we have to change the code (not a good option) or change our var.yaml file by extracting only the observations part.

**Comment by guillaumevernieres** [comment]
@mjhossen , does it work when you just provide as input the obs part of the var.yaml?

**Comment by mjhossen** [comment]
@guillaumevernieres No, there is an indent issue. In the var.yaml, observations is under cost function. So I think, we need another "for loop" under cost function in the ```gen_eva_obs_yaml.py```. I am thinking to make another python script for marine DA. In the meantime, I just extract only the observation parts manually. It works!

**Comment by mjhossen** [comment]
@guillaumevernieres I am finally able to produce some figures using GDASApp eva. It requires more effort to tune up the plot, for example, rewrite the python script so that observations can be read directly from the var.yaml file in the exp dir. I will be working on it. $dynami_vmin/vmax in EVA is not working, I will contact to Cory.
![Screen Shot 2022-11-08 at 9 23 52 AM](https://user-images.githubusercontent.com/65732322/200590919-dbecbb4c-5d2f-43dc-8a2a-17fcc0ff725b.png)
![Screen Shot 2022-11-08 at 9 24 39 AM](https://user-images.githubusercontent.com/65732322/200590923-1ccace33-349e-4a9c-bed2-730fab8c293d.png)
![Screen Shot 2022-11-08 at 9 25 09 AM](https://user-images.githubusercontent.com/65732322/200590927-865ae40a-a975-4a2c-968b-934e9adc7691.png)

**Comment by guillaumevernieres** [comment]
ok, thanks for the update @mjhossen .
