### ISSUE TITLE
Generate p8 IC for a few test cases that resulted in unstable ~35 day forecast

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#418]
Pinging @ShastriPaturi to remember to properly fill in a description for that issue. 

**From communication with modelling team:**
The log files are located at:
```
/scratch1/NCEPDEV/stmp2/Wei.Li/ROTDIRS/ctl_EMC4/logs/2020070600
/scratch1/NCEPDEV/stmp2/Wei.Li/ROTDIRS/ctl_EMC4/logs/2020080500
/scratch1/NCEPDEV/stmp2/Wei.Li/ROTDIRS/ctl_EMC4/logs/2020081500
```

@hyunchul386 , could you re-run 2020-07 to 2020-08 with p8?

**Comment by guillaumevernieres** [comment]
@hyunchul386 , is that run complete?

**Comment by hyunchul386** [comment]
The run is completed for 30 day and running, and the work directory is /work/noaa/marine/Hyun-Chul.Lee/emc6/

**Comment by guillaumevernieres** [comment]
@hyunchul386 , was it communicated to @AvichalMehra-NOAA and @yangfanglin ?

Did you look at/document that run somewhere?

**Comment by hyunchul386** [comment]
I haven't communicated with them and don't have info for the documents.

**Comment by ShastriPaturi** [comment]
@hyunchul386 this a deliverable. We need a document and some plots for @AvichalMehra-NOAA and @yangfanglin, with a follow-up email.

**Comment by hyunchul386** [comment]
I will prepare a documents with some plots for emc6

**Comment by hyunchul386** [comment]
The short version is ready
https://docs.google.com/presentation/d/1qJABUQXbWQtAXrPdOz-EkOHXE7pik1-BfyZ4QrcK5B8/edit#slide=id.p

The previous version is
https://docs.google.com/presentation/d/1qAyaz2JjyFUD9my0fmdhjtdI43d5EJBzErHiQsI_MS4/edit#slide=id.g1a769ea618f_0_266

**Comment by hyunchul386** [comment]
Hyun-Chul Lee - NOAA Affiliate, Yesterday 10:20 AM
On the ioda-plots, I thought that the code of ioda-plots calculate the (o-b) of the experiments, not |o-b|. Is this correct?

Hyun-Chul Lee - NOAA Affiliate, 37 min
@Guillaume Vernieres - NOAA Federal  I guess you can see the updated icec data for 2020-09-05. in my eye, emc6 is clearly better than emc4 in terms of the extend, but less than NSIDC ( may be due to the warm bias in polar region). Let me know any questions/comments.

Guillaume Vernieres - NOAA Federal, 33 min
I saw that. Did you generate the figures for the IC's Avichal wants?
also, I don't know how to interpret your bias figures of slide 3

Hyun-Chul Lee - NOAA Affiliate, 32 min
The runs of emc5/emc6 generated model IC's in ~/rst, is that the IC's for Avichal?
I will remove it.

Guillaume Vernieres - NOAA Federal, 31 min
they needed 3 specific dates

Hyun-Chul Lee - NOAA Affiliate, 30 min
Would you let me know the dates? I will check it.

Guillaume Vernieres - NOAA Federal, 30 min
ha! don't remove slide 3!
just the bias diff

Hyun-Chul Lee - NOAA Affiliate, 30 min
Okay revive it

Guillaume Vernieres - NOAA Federal, 28 min
I removed the one I don't know how to interpret ... put them back if you know what conclusion to draw out of the bias diff ...

Shastri Paturi - NOAA Affiliate, 26 min
The dates are in the godas issue

Hyun-Chul Lee - NOAA Affiliate, 25 min
In rmse, I think, the color would indicate the superiority

Guillaume Vernieres - NOAA Federal, 24 min
that's a weird choice of words, but yes.
it's not as bad as what we thought, maybe I got confused with the bias plots.
still, lots of red for sst
and unless the plots are wrong, sea ice is still garbage.

Hyun-Chul Lee - NOAA Affiliate, 22 min
But , in SST, the red is generally along the coastal region, which means we can improve it.

Shastri Paturi - NOAA Affiliate, 21 min
The sea-ice plot of NSIDC cannot be used for comparison

Guillaume Vernieres - NOAA Federal, 21 min
why not?

Shastri Paturi - NOAA Affiliate, 21 min
The color plot and the scale is different

Guillaume Vernieres - NOAA Federal, 20 min
ha! yes
but it's better than yesterday
Agree with you though, that needs to be cleaned up. What did you use to plot the seaice for emc6 and emc4 @Hyun-Chul Lee - NOAA Affiliate ?

Shastri Paturi - NOAA Affiliate, 19 min
I need a timeline for you to complete the plots to be sent to Avichal and Fanglin

Hyun-Chul Lee - NOAA Affiliate, 19 min
Indeed, NSIDC data is monthly data, not apple to apple.

Guillaume Vernieres - NOAA Federal, 19 min
ha ...

Hyun-Chul Lee - NOAA Affiliate, 19 min
I used scripts in godas/monitoring/

Guillaume Vernieres - NOAA Federal, 18 min
why not just plot the obs that we use?

Shastri Paturi - NOAA Affiliate, 18 min
As I mentioned in my comment on FRiday and also shared with you my plotting script
Now the NSIDC data (daily) is in R2D2
A scatter plot can be compared

Hyun-Chul Lee - NOAA Affiliate, 16 min
Okay, would you let me know more detail notes for the usage of the scripts?

Shastri Paturi - NOAA Affiliate, 16 min
You should have asked me on Friday...
We are losing time on this discussion

Hyun-Chul Lee - NOAA Affiliate, 15 min
You said that At that R2D2 data covered only 2019.

Shastri Paturi - NOAA Affiliate, 15 min
I need a timeline from you
Also, Guillaume has asked for var.yaml and you mentioned that will run one cycle by saving the SCRATCH dir.
Do you have that?
emc4 and emc6

Guillaume Vernieres - NOAA Federal, 14 min
+1 for var.yaml ...

Hyun-Chul Lee - NOAA Affiliate, 8 min
As mentioned Guillaume, emc4 could not re-generated, and as you mentioned, due to the update spack-stack (Nov 15th), emc6 also can not be re-generated with the exact same configuration. I have the var.yaml from emc6's ~/godas/soca, which is /work/noaa/marine/Hyun-Chul.Lee/emc_ref2_check/SCRATCH/2020090600/run.var/var.yaml. This is from the same ~godas/soca of emc6, but difference soca-sci branch and usf configuration.

Shastri Paturi - NOAA Affiliate, 2 min
All this information will be lost in 24 hrs. Can you put this on the github issue?

**Comment by hyunchul386** [comment]
Now NSIDC daily data is available in /R2D2 by @ShastriPaturi. So I will replace the sea-ice data comparison between emc6/emc4 and daily NSIDC data today (2022-12-20/21).

**Comment by guillaumevernieres** [comment]
How is copy/pasting google chat without summarizing useful @hyunchul386 ?

**Comment by hyunchul386** [comment]
I will summarize it

**Comment by hyunchul386** [comment]
ICEC plots were updated in comparisons with NSICD daily data in 20220706/20220805/20220815/20220905.
