### ISSUE TITLE
SST from drifters (PHOD-AOML)

### ISSUE THREAD

**Issue by ShastriPaturi** [NOAA-EMC/godas#442]
- [x] Download data from PHOD-AOML
- [x] Develop a converter (ask @guillaume for his already existing converter ... it may or may not be a good starting point!)
- [x] Convert to IODA format

**Comment by mjhossen** [comment]
Drifter data is available at https://www.aoml.noaa.gov/phod/gdp/interpolated/data/all.php

**Comment by guillaumevernieres** [comment]
@mjhossen , I copied my script here: `/work2/noaa/da/gvernier/tmp`
I'm not sure how useful this will be, this will depend on the organization of the drifter obs files that you are using. It may be useful if the data is organized in 1 file per drifter.

Here's the issue that I remember from the drifter obs:
The original obs that I worked with from the GDP were organized as 1 file per drifter, and since the life pan of a drifter can be multiple years, simply converting the drifter files is not practical. 
Here what I did instead:
- read all the drifter obs/files in memory, don't do that on the login node!
- generate daily ioda files from the concatenated drifter data set

**Comment by mjhossen** [comment]
Thanks @guillaumevernieres

**Comment by mjhossen** [comment]
@guillaumevernieres Do you suggest to create daily ioda files for all drifter i.e to store daily data for all drifter in a single file irrespective of drifter ID?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Do you suggest to create daily ioda files for all drifter i.e to store daily data for all drifter in a single file irrespective of drifter ID?

yes

**Comment by mjhossen** [comment]
Modified the drifter scripts developed by @guillaumevernieres to make it compatible for the 6 hourly interpolated data ([gdp_jul22_ragged_6h.nc](  https://www.aoml.noaa.gov/phod/gdp/interpolated/data/all.php)). Here are some plots: 
![Screen Shot 2023-01-24 at 4 19 48 PM](https://user-images.githubusercontent.com/65732322/214437107-50a02276-c88d-4ce3-8c4a-32caf92f8788.png)
![Screen Shot 2023-01-24 at 4 20 07 PM](https://user-images.githubusercontent.com/65732322/214437105-7a497261-2547-4c79-a831-aa5df655b06b.png)

**Comment by mjhossen** [comment]
in r2d2 database, the sst_drifter is available until 2020-09-30. Going to convert drifter data from October 2020 to Dec 2022.

**Comment by mjhossen** [comment]
Completed drifter data conversion into IODA for the period of October 2020 to July 2022.  
![Screen Shot 2023-01-26 at 2 03 32 PM](https://user-images.githubusercontent.com/65732322/214926497-30a1fd36-3d72-4a7e-a0dd-49529a6ce95b.png)
![Screen Shot 2023-01-26 at 2 03 50 PM](https://user-images.githubusercontent.com/65732322/214926504-bdbfbb2d-c116-4c79-949c-39601b961598.png)
![Screen Shot 2023-01-26 at 2 04 19 PM](https://user-images.githubusercontent.com/65732322/214926506-05ab0139-ff9c-4202-89e7-6cbca86e2922.png)

**Comment by guillaumevernieres** [comment]
Correct me if I'm wrong @ShastriPaturi and @mjhossen , but I believe this issue was completed. Closing!

**Comment by mjhossen** [comment]
> Correct me if I'm wrong @ShastriPaturi and @mjhossen , but I believe this issue was completed. Closing!

Yes, completed.
